#!/usr/bin/env python
r"""Regenerate paper/macros_ag.tex from results/aliasguard.json so NO AliasGuard number in
the paper is hand-entered.  Run: python paper/sync_macros.py ; main.tex \inputs the result.
paper/check_consistency.py fails the build if this file is stale vs. the committed JSON."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
J = json.loads((ROOT / "results" / "aliasguard.json").read_text())

S = J["summary"]
C = J["certificate"]
TW2 = J.get("nd_2d", {})
TW3 = J.get("nd_3d", {})


def _load(name):
    p = ROOT / "results" / name
    return json.loads(p.read_text()) if p.exists() else None


def _pct(x):
    return f"{round(float(x) * 100)}\\%"


def r2(x):
    return f"{x:.2f}"


def r3(x):
    return f"{x:.3f}"


def held(method, typ="near"):
    return S[method]["heldout"][typ]


ag = held("aliasguard")
ci = (ag["ci_hi"] - ag["ci_lo"]) / 2.0

# certificate: how many scenarios give a NON-VACUOUS (<1) guarantee (rest are reported
# vacuous, not hidden) -- and whether the 2-D held-out margin is statistically separated.
_cv = [x for x in C["aliasguard"]["certified_values"] if x is not None]
_nv = sum(1 for x in _cv if x < 1.0)
def _nd(tw, method):
    return tw.get("summary", {}).get(method, {}).get("mean", float("nan"))


def _nd_sep_phrase(tw):
    return "separated from every baseline" if tw.get("all_separated") else \
        "separated from random but not every baseline"

lines = [
    "% AUTO-GENERATED by paper/sync_macros.py from results/aliasguard.json -- do not edit.",
    f"\\newcommand{{\\AGheld}}{{{r2(ag['mean'])}}}",           # held-out near, AliasGuard
    f"\\newcommand{{\\AGheldCI}}{{{r2(ci)}}}",
    f"\\newcommand{{\\AGrand}}{{{r2(held('random_jitter')['mean'])}}}",
    f"\\newcommand{{\\AGds}}{{{r2(held('ds_optimal')['mean'])}}}",   # exact D_s baseline
    f"\\newcommand{{\\AGcert}}{{{r2(C['aliasguard']['certified_mean'])}}}",
    f"\\newcommand{{\\AGcertR}}{{{r2(C['random_jitter']['certified_mean'])}}}",
    f"\\newcommand{{\\AGcertD}}{{{r2(C['ds_optimal']['certified_mean'])}}}",
    f"\\newcommand{{\\AGtwoD}}{{{r2(_nd(TW2, 'aliasguard'))}}}",
    f"\\newcommand{{\\AGtwoDR}}{{{r2(_nd(TW2, 'random_jitter'))}}}",
    f"\\newcommand{{\\AGtwoDds}}{{{r2(_nd(TW2, 'ds_optimal'))}}}",
    f"\\newcommand{{\\AGthreeD}}{{{r2(_nd(TW3, 'aliasguard'))}}}",
    f"\\newcommand{{\\AGthreeDR}}{{{r2(_nd(TW3, 'random_jitter'))}}}",
    f"\\newcommand{{\\AGthreeDds}}{{{r2(_nd(TW3, 'ds_optimal'))}}}",
    f"\\newcommand{{\\AGthreeDsep}}{{{_nd_sep_phrase(TW3)}}}",
    # honest off-target degradation (used in the limitations sentence)
    f"\\newcommand{{\\AGbroad}}{{{r2(held('aliasguard', 'broadband_ood')['mean'])}}}",
    f"\\newcommand{{\\AGcertNV}}{{{_nv}}}",                    # non-vacuous cert count
    f"\\newcommand{{\\AGcertTot}}{{{len(_cv)}}}",              # total scenarios
    f"\\newcommand{{\\AGtwoDsep}}{{{_nd_sep_phrase(TW2)}}}",
]

# nonlinear (trained-network) numbers -- also auto-generated, never hand-entered
NL = _load("nonlinear.json")
if NL and "summary" in NL:
    nsum = NL["summary"]

    def nlget(arch, key, default=0.0):
        return (nsum.get(arch, {}) or {}).get(key, default)

    def nlcorr(arch):
        return (nsum.get(arch, {}) or {}).get("pattern_corr_median", 0.0)

    lines += [
        f"\\newcommand{{\\NLffmatch}}{{{_pct(nlget('ffmlp', 'exact_match_rate'))}}}",
        f"\\newcommand{{\\NLsimatch}}{{{_pct(nlget('siren', 'exact_match_rate'))}}}",
        f"\\newcommand{{\\NLfftop}}{{{_pct(nlget('ffmlp', 'top3_match_rate'))}}}",
        f"\\newcommand{{\\NLffcorr}}{{{r2(nlcorr('ffmlp'))}}}",
        f"\\newcommand{{\\NLsicorr}}{{{r2(nlcorr('siren'))}}}",
        f"\\newcommand{{\\NLblcorr}}{{{r2(nlcorr('bandlimited'))}}}",
        f"\\newcommand{{\\NLffn}}{{{int(nlget('ffmlp', 'n_runs') or 0)}}}",
        f"\\newcommand{{\\NLffdrift}}{{{r2(nlget('ffmlp', 'ntk_rel_drift_median') or 0.0)}}}",
        f"\\newcommand{{\\NLsidrift}}{{{r2(nlget('siren', 'ntk_rel_drift_median') or 0.0)}}}",
    ]
else:
    lines += ["\\newcommand{\\" + n + "}{\\textrm{[pending]}}" for n in
              ("NLffmatch", "NLsimatch", "NLfftop", "NLffcorr", "NLsicorr", "NLblcorr",
               "NLffn", "NLffdrift", "NLsidrift")]

# 2-D image numbers (headline excess of coherent over no-alias control)
IM = _load("image2d_aliasing.json")
imx = (IM or {}).get("headline_excess") or {}
ima = (IM or {}).get("part_a_linear") or {}
lines += [
    f"\\newcommand{{\\IMexcess}}{{{r3(imx['excess_mean']) if 'excess_mean' in imx else '[pending]'}}}",
    f"\\newcommand{{\\IMrate}}{{{_pct(imx['lattice_gt_random_rate']) if 'lattice_gt_random_rate' in imx else '[pending]'}}}",
    f"\\newcommand{{\\IMfold}}{{{_pct(ima['fold_exact_rate']) if 'fold_exact_rate' in ima else '[pending]'}}}",
]

# real-signal numbers (CO2 / speech) -- from results/real_*.json, never hand-entered
CO2 = _load("real_co2.json")
SPE = _load("real_speech.json")


def real_rmse(d, method):
    return (((d or {}).get("methods", {}) or {}).get(method, {}) or {}).get("rmse_mean")


co2_ls, co2_ora = real_rmse(CO2, "ls_periodogram"), real_rmse(CO2, "oracle")
spe_ora = real_rmse(SPE, "oracle")
lines += [
    f"\\newcommand{{\\NumCoTwoLS}}{{{r3(co2_ls) if co2_ls is not None else '[pending]'}}}",
    f"\\newcommand{{\\NumCoTwoOracle}}{{{r3(co2_ora) if co2_ora is not None else '[pending]'}}}",
    f"\\newcommand{{\\NumSpeechOracle}}{{{r2(spe_ora) if spe_ora is not None else '[pending]'}}}",
]

# Program 3: trained-INR sampling-design win + certificate-predicts-winner (never hand-entered).
# AliasGuard DESIGNS the training samples; we report held-out PSNR, #baselines beaten (paired,
# significant), and Spearman(certificate, trained error) -- for FF-MLP AND SIREN.
INR = _load("inr_design.json")


def _inr_psnr(arch):
    return ((INR or {}).get("summary", {}).get(arch, {}) or {}).get("aliasguard", {}).get("psnr_mean")


def _inr_wins(arch):
    p = ((INR or {}).get("paired", {}) or {}).get(arch, {}) or {}
    return sum(1 for d in p if p[d].get("significant_win")), len(p)


def _inr_spear(arch):
    return (((INR or {}).get("cert_predicts_winner_spearman", {}) or {}).get(arch, {}) or {}).get("rho_within_mean")


if INR and "summary" in INR:
    ffw, ffn = _inr_wins("ffmlp")
    siw, sin = _inr_wins("siren")
    lines += [
        f"\\newcommand{{\\INRffPSNR}}{{{r2(_inr_psnr('ffmlp'))}}}",
        f"\\newcommand{{\\INRsiPSNR}}{{{r2(_inr_psnr('siren'))}}}",
        f"\\newcommand{{\\INRffWins}}{{{ffw}}}",
        f"\\newcommand{{\\INRffBaselines}}{{{ffn}}}",
        f"\\newcommand{{\\INRsiWins}}{{{siw}}}",
        f"\\newcommand{{\\INRsiBaselines}}{{{sin}}}",
        f"\\newcommand{{\\INRffSpear}}{{{r2(_inr_spear('ffmlp'))}}}",
        f"\\newcommand{{\\INRsiSpear}}{{{r2(_inr_spear('siren'))}}}",
    ]
else:
    lines += ["\\newcommand{\\" + n + "}{\\textrm{[pending]}}" for n in
              ("INRffPSNR", "INRsiPSNR", "INRffWins", "INRffBaselines", "INRsiWins",
               "INRsiBaselines", "INRffSpear", "INRsiSpear")]

out = ROOT / "paper" / "macros_ag.tex"
out.write_text("\n".join(lines) + "\n")
print("wrote", out)
print("\n".join(lines[1:]))
