#!/usr/bin/env python
r"""Regenerate paper/macros_ag.tex from results/aliasguard.json so no AliasGuard number in
the paper is hand-entered.  Run: python paper/sync_macros.py ; then \input it in main.tex.
The build (paper/build.sh) fails if this file is stale vs. the committed JSON."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
J = json.loads((ROOT / "results" / "aliasguard.json").read_text())

C = J["C_heldout"]["methods"]
G = J["G_certificate"]["methods"]
F = J["F_2d"]


def r2(x):
    return f"{x:.2f}"


lines = [
    "% AUTO-GENERATED by paper/sync_macros.py from results/aliasguard.json -- do not edit.",
    f"\\newcommand{{\\AGheld}}{{{r2(C['aliasguard_heldout']['max_aliasability'])}}}",
    f"\\newcommand{{\\AGheldCI}}{{{r2(C['aliasguard_heldout']['max_aliasability_ci'])}}}",
    f"\\newcommand{{\\AGrand}}{{{r2(C['random_jitter']['max_aliasability'])}}}",
    f"\\newcommand{{\\AGeopt}}{{{r2(C['e_optimal']['max_aliasability'])}}}",
    f"\\newcommand{{\\AGmis}}{{{r2(C['aliasguard_misspecified']['max_aliasability'])}}}",
    f"\\newcommand{{\\AGcert}}{{{r2(G['aliasguard']['certified_max_aliasability'])}}}",
    f"\\newcommand{{\\AGcertR}}{{{r2(G['random_jitter']['certified_max_aliasability'])}}}",
    f"\\newcommand{{\\AGtwoD}}{{{r2(F['aliasguard']['max_aliasability'])}}}",
    f"\\newcommand{{\\AGtwoDR}}{{{r2(F['random']['max_aliasability'])}}}",
]
out = ROOT / "paper" / "macros_ag.tex"
out.write_text("\n".join(lines) + "\n")
print("wrote", out)
print("\n".join(lines[1:]))
